# Generated by Django 6.0.3 on 2026-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-month_id']},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='invoice_google',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
