# Generated by Django 6.0.3 on 2026-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detailtype_options_alter_platowner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'exchange_rate',
                'ordering': ['-year', '-month', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'currency'), name='exchange_rate_unique_period_currency')],
            },
        ),
    ]
